//arnoldSchwarzenegger, gilbertGottfried, billClinton, dannyDevito, georgeBush, leonardNimoy,  alanRickman, billGates, billNye

let quotes = {
  arnoldSchwarzenegger: [
    "If I can see it and believe it, then I can achieve it.",
    "I was going to give a graduation speech in Arizona this weekend. But with my accent I was afraid they would try to deport me.",
    "Its simple, if it jiggles, its fat.",
    "Get to the Chopper!",
    "Who is your daddy and what does he do?",
    "Yes, I am a robot. Next question?",
    "Consider that a divorce!",
    "Hasta lavista, baby!",
    "It's not a tumor",
    "You make too uch noise! Has to be very quite in here, like in a Church!",
    "You will get more from being a peacemaker than a warrior",
  ],

  gilbertGottfried: [
    "I changed the face of comedy. I used to be funny",
    "Im used to explaining to people why my jokes were funny.",
    "The pressure to being a comedian is being funny, but Ive gien that up, so there is no pressure whatsoever.",
    "Last night I was having dinner with Charles Manson and in the middle of dinner he turned to me and said, Is it hot in here or am I crazy",
    "What do you get when you cross a genius with a hooker, a know it all.",
    "Well I play Jews and parrots. Parrots are how ive branched out",
    "You never know what people will choose to be offended by",
    "If someone else is paying for it, food just tastes a lot better.",
    "I just dont accept midgets as human beings, Theres only so much polotical correctness I can accept",
    "Everytime something pops in my head, I think twice about it and I do it anyway.",
    "Nothing can help my comdey",
    "I always try to avoid anything that has to do with my life.",
    "If the police ever try to pick me up, Michael jackson told me I can hide out at his house.",
    "What do Japanese Jews love to eat. Hebrew National Tsunami.",
    "Im known for my slightly inappropriate remarks.",
  ],

  billClinton: [
    "I may not have been the greatest president, but Ive had the most fun.",
    "I dont know wheter its the finest public housing in America or the crown jewel of the American penal system.",
    "When I was in England, I experimented with marijuana a time or two, and I did not like it. I didt inhale and never tried it again.",
    "Being president is like running a cemetery: youve got a lot of people under you and nobodys listening",
    "It depends on what the meaning of the word is is",
    "You know if I were a single man, I might ask that mummy out. Thats a good looking mummy.",
    "Politics gives guys so much power that they tend to behave badly around women. I hope I never get into that.",
    "There were a lot of times when we were alone, but I never really thought we were.",
    "Sometimes I feel like the fire hydrant looking at a pack of dogs",
    "It wasnt my finest hour. It wasnt even my finest hour and a half.",
    "It depends on how you define alone",
    "Chances this will not become a meme, ZERO",
  ],

  dannyDevito: [
    "A tree falls the way it leans. Be careful the way you lean",
    "I dont look ahead. Im right hereIts fun to be on the edge.",
    "I am self centered. I just adore myself",
    "What do you call 500 lawyers lying on the bottom of the ocean. A good start",
    "There are only three things with that kind of unconditional acceptance. Dogs donuts and money",
    "I climed like a billion stairs. Its not like I can take them two at a time.",
    "Of course Ive got lawyes. They are like nuclear weapons",
    "Getting old is a gift",
    "Everybody need money. Thats why they acll it money",
    "Fill me up with cream. Turn me into a cannoli.",
  ],

  georgeBush: [
    "They misunderestimate me.",
    "Thank you, your holliness. Awesome speech.",
    "Ill be long gone before some smart person ever figures out what happened inside this Oval office",
    " So long as Im the president my measure of success is victory",
    "Ive abandoned free market principles to save the free market system",
    "Goodbye from the worlds biggest polluter.",
    "In terms of the economy, look I inherited a recession, I am ending on a recession",
    "People say, well do you ever hear any other voices other than ike a few people. Of course I do",
    "Weve got a lot of relations with countries in our neighborhood",
    "Lets make sure there is certainty during uncertain times in our economy",
    "A lot of times in politics you have people look you in the eye and tell you whats not on their mind",
    " Theres no question about it. Wall Street got drunk. It got drunk and now its got a hangover",
  ],

  leonardNimoy: [
    "Warp Factor 8! Arbys closes in 10 mintes.",
    "Set phasers to fabulous!",
    "We have been hijacked by Somali Pirates",
    "My Baby Daddy is a Vulcan on the next Maury",
    "Insufficient facts always invite danger",
    "Live long and Prosper",
    "Insufficient facts always invite danger",
    "I know where Im going, and I know where Ive been",
  ],

  alanRickman: [
    "If only life could be a little more tender and art a little more robust",
    "I think there should be laughs in everytihng. Sometimes, its a slammed door, a pie in the face or just a recognition of our frailties",
    "Talent is an accident of genes and a responsibility.",
    "Ive never been able to plan my life. I just lurch from indecision to indecision",
  ],

  billGates: [
    "Be nice to nerds. Chances are you will end up working for one.",
    "In China when you are one in a million, there are 1300 people just like you.",
    "There are people who do not like capitalism, and people who do not like PCs. But there is no one who lies the PC who does not like Microsoft.",
  ],

  billNye: [
    "If the Earth gets hit by an asteroid, its game over. Its control alt delete for civilization.",
    "Humor is everywhere in that theres irony in just about anything a human does.",
    "The more you find out about the world, the more opportunities there are to laugh at it.",
  ],

  philMcgraw: [
    "Its better to be healthy alone than sick with someone else.",
    "You dont need a ropte to pinch a stangers butt.",
    "You dont need a pack of wild horses to learn how to make a sandwich",
    "Common sense needs to be more common.",
    "Eighty percent of all questoins are statemnts in disguise",
    "Stand up and walk out of your history",
    "Nothing is funnier to me than lauging at myself.",
    "No matter how flat you make a pancake, its still got two sides.",
    "I didnt just come in on a load of turnips!",
    "Im not a politician",
  ],
};
